name: Lint

on:
  pull_request:
    branches: ['trunk']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.2'
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
